# A partir do exemplo de workflow estático do github
name: Deploy do conteúdo
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Checar existencia do index.html
        run: |
           if [ ! -f public/index.html ]; then
            echo "index.html não foi encontrado no diretório /public"
            exit 1
          fi
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'
      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
